#!/usr/bin/env bash
# Interactive .env setup. Prompts for each required variable, then writes
# a plaintext .env.local that Next.js will pick up automatically.
#
# Usage:
#   ./scripts/make-env.sh             # writes .env.local
#   OUT_FILE=.env.development ./scripts/make-env.sh
#
# Each prompt shows the existing value (if any) as the default — press Enter
# to keep it. Type a new value to overwrite. Type "-" to clear it.

set -euo pipefail

OUT_FILE="${OUT_FILE:-.env.local}"

# name | description | secret(yes|no)
VARS=(
  "NEXT_PUBLIC_SUPABASE_URL|Supabase project URL (https://xxxx.supabase.co)|no"
  "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY|Supabase anon/publishable key|no"
  "SUPABASE_SERVICE_ROLE_KEY|Supabase service role key (server only)|yes"
  "BLOOM_AUTH_SECRET|Random secret for wallet auth JWT signing (32+ chars)|yes"
  "COINMARKETCAP_API_KEY|CoinMarketCap API key (for /api/gooddollar price)|yes"
  "FONBNK_SOURCE|Fonbnk source ID (e.g. 10Uvdd7H)|no"
  "FONBNK_URL_SECRET|Fonbnk URL signing secret|yes"
  "NEXT_PUBLIC_WC_PROJECT_ID|WalletConnect Cloud project ID (optional, leave blank to disable WC)|no"
)

# Load current values from existing file if present
declare -A CURRENT
if [ -f "$OUT_FILE" ]; then
  echo "Found existing $OUT_FILE — values will be shown as defaults."
  while IFS='=' read -r k v; do
    [ -z "$k" ] && continue
    case "$k" in \#*) continue;; esac
    # strip surrounding quotes
    v="${v%\"}"; v="${v#\"}"
    CURRENT["$k"]="$v"
  done < "$OUT_FILE"
fi

TMP_FILE="$(mktemp)"
echo "# Generated by scripts/make-env.sh on $(date)" > "$TMP_FILE"

for entry in "${VARS[@]}"; do
  IFS='|' read -r name desc secret <<< "$entry"
  default="${CURRENT[$name]:-}"

  echo ""
  echo "• $name"
  echo "  $desc"

  if [ -n "$default" ]; then
    if [ "$secret" = "yes" ]; then
      echo "  current: ********${default: -4}"
    else
      echo "  current: $default"
    fi
  fi

  if [ "$secret" = "yes" ]; then
    read -r -s -p "  value (Enter = keep, '-' = clear): " input
    echo ""
  else
    read -r -p "  value (Enter = keep, '-' = clear): " input
  fi

  if [ "$input" = "-" ]; then
    value=""
  elif [ -z "$input" ]; then
    value="$default"
  else
    value="$input"
  fi

  if [ -n "$value" ]; then
    # Escape any double-quotes in the value
    escaped="${value//\"/\\\"}"
    printf '%s="%s"\n' "$name" "$escaped" >> "$TMP_FILE"
  else
    printf '# %s=\n' "$name" >> "$TMP_FILE"
  fi
done

mv "$TMP_FILE" "$OUT_FILE"
chmod 600 "$OUT_FILE"
echo ""
echo "✓ Wrote $OUT_FILE"
echo "  Next: restart dev server, or push to Vercel via ./scripts/push-env-to-vercel.sh"
